name: Build DLS
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-StandaloneWindows64

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.0.0f1
          targetPlatform: StandaloneWindows64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StandaloneWindows64
          path: build/StandaloneWindows64
